### ISSUE TITLE
castlemock cannot auto import projects from swagger yaml files defined in dockerfile

### ISSUE THREAD

**Issue by medaoutir** [castlemock/castlemock#651]
**castlemock cannot auto import projects from swagger yaml files**
castlemock cannot auto import projects from swagger yaml files defined in dockerfile.

**To Reproduce**
Given this dockerfile:

```
FROM castlemock/castlemock:v1.65

COPY ./sources/swagger/* /opt/castlemock/mocks/

ENV PATH=$PATH:/opt/castlemock/bin

CMD ["castlemock", "start", "-autoimport"]
```
and this docker-compose file:

```
version: '3.8'

services:
  mock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ewl
    ports:
      - 1080:8080
```
I'm facing this error:

> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "castlemock": executable file not found in $PATH: unknown

when I run **docker-compose up --build -d**

So that mean that the executable file doesn't exists in **/opt/castlemock/bin** folder, where I can find it please ?and **-autoimport** option is correct to auto import projects from swagger yaml files defined in my Dockerfile as described above ?
Thanks for your help.

**Desktop (please complete the following information):**

- OS: Windows 11
