### ISSUE TITLE
Support for declarative configuration

### ISSUE THREAD

**Issue by php-coder** [castlemock/castlemock#79]
Hi, thank you for your work on this project!

I'd like to have a way to specify some configuration to avoid manual configuration and have fully-functional mock server right after startup.

In my case, I need to create a SOAP project and import WSDL file into it.

Here some possible ways to implement it:
- one can pass desired configuration via environment variables:
  - `PROJECT_1_NAME=FooService`
  - `PROJECT_1_TYPE=soap`
  - `PROJECT_1_WSDL_PATH=/path/to/wsdl`
- another way is to have a configuration file in predefined location that could be mounted inside docker container by using `-v` option. This file may look like:
    ```yaml
    projects:
    - name: FooService
      description: Mock for Foo Service
      type: soap
      wsdl-file: /path/to/wsdl/inside/a/container
    ```
    The last approach is more flexible.

What do you think?
